"""Conversations with the agent. Every thread belongs to one user; others get 404, not 403,
so thread ids cannot be probed."""

import logging
from datetime import UTC, datetime, timedelta
from typing import Annotated, Any, Literal
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Request, Response, status
from langchain_core.messages import AIMessage, HumanMessage, ToolMessage
from pydantic import BaseModel, Field, computed_field
from sqlalchemy import select, update

from .. import approvals, apps, audit, background, questions
from ..auth import CurrentPrincipal
from ..chat_files import attached_note
from ..deletions import THREAD_WAIT_S, finished_or_accepted, start_thread_deletion
from ..deps import Session
from ..models import (
    ACTIVE_RUN_STATUSES,
    ChatFile,
    InputRequest,
    OutcomeEvaluation,
    Run,
    RunEvent,
    Thread,
)
from ..not_blank import MessageText
from ..runs import store
from ..runs.events import (
    MAX_TOOL_ARGS,
    MAX_TOOL_OUTPUT,
    USER_MESSAGE_PREFIX,
    citations,
    json_safe,
    tool_sources,
    web_actions,
)
from ..users import CurrentUser

router = APIRouter(prefix="/v1/threads", tags=["threads"])
logger = logging.getLogger(__name__)


class ThreadOut(BaseModel):
    id: UUID
    title: str
    created_at: datetime
    updated_at: datetime
    # Its active run's status, if it has one: queued, running, or waiting (for the person)
    run_status: str | None = None
    # "ask" (Ask before acting) or "auto" (Act, ask when unsure)
    permission_mode: str = approvals.DEFAULT_MODE
    # A background task's chat: the chat that started it (background.py)
    parent_id: UUID | None = None


class Step(BaseModel):
    """A tool the agent used while answering (the same fields as the `tool.*` run events)."""

    id: str
    name: str
    args: Any = None
    status: Literal["running", "success", "error", "declined"] = "running"
    # The pages it consulted: a web search's sources, the router search's results
    sources: list["Source"] = []
    # A question to the person (`ask_user`): what they answered, as the agent read it
    output: str | None = None
    # A connector tool with a View (MCP Apps): the View, the arguments and the result it's sent
    app: dict[str, Any] | None = None
    # A read of a plugin's skill: the plugin it came from (plugin_skills.py)
    plugin: str | None = None
    # A background task it started (background.py): the task's chat
    task: str | None = None


class Source(BaseModel):
    url: str
    title: str | None = None


class MessageOut(BaseModel):
    role: Literal["user", "assistant"]
    content: str
    # On the first answer of a turn: the tools the agent used for that turn
    steps: list[Step] = []
    # The pages this answer cites (the web search's citations), with titles
    citations: list[Source] = []
    # On a question: the run that answered it (its message's id, runs/executor.py)
    run_id: str | None = None
    # On a question: the files attached to it; on the first answer of a turn: the files the
    # turn's environment shared (chat_files.py)
    files: list["ChatFileOut"] = []
    # On a turn's last answer, when its task has a rubric: the grader's verdict (outcomes.py)
    evaluation: "Evaluation | None" = None
    # On a question: Gen9 wrote it, not the person (a background task's notice, background.py)
    notice: bool = False
    # On a question: a scheduled task's grader wrote it, its findings for the next try
    # (outcomes.py), not the person
    revision: bool = False
    # On a turn's first answer: earlier messages were summarized to make room (the context
    # budget, explore/context/NOTES.md)
    summarized: bool = False

    @computed_field
    @property
    def ai_generated(self) -> bool:
        """Gen9's answers are generated by an AI system, marked so in a machine-readable way
        wherever a message is given out, the export included (AI Act Art. 50(2); docs/ai-act.md)."""
        return self.role == "assistant"


class Evaluation(BaseModel):
    """A grader's verdict on a turn's answer: each criterion met or not and why."""

    result: Literal["satisfied", "needs_revision", "failed"]
    explanation: str
    criteria: list[dict[str, Any]]
    # Which try of its firing it graded, from 0
    iteration: int


class ChatFileOut(BaseModel):
    """A chat's file, without its content: `GET …/files/{id}` serves it."""

    id: str
    name: str
    size: int
    media_type: str
    # Attached by the person, or made by Gen9 in the chat's environment
    origin: Literal["upload", "output"] = "upload"

    @computed_field
    @property
    def ai_generated(self) -> bool:
        """A file Gen9 made is marked as an AI system's (AI Act Art. 50(2); docs/ai-act.md)."""
        return self.origin == "output"


class ActiveRun(BaseModel):
    """The run still working on this thread: follow it at `…/runs/{id}/stream`."""

    id: UUID
    status: str
    message: str
    # Its message is a background task's notice, not the person's
    notice: bool = False
    # Its message is a grader's findings (a scheduled task's next try), not the person's
    revision: bool = False


class BackgroundTaskOut(BaseModel):
    """A task this chat's agent started in the background: its chat and its latest run's
    status (background.py)."""

    id: UUID
    title: str
    status: str | None
    created_at: datetime
    # Its end was told to the chat (a notice's run exists), or needs no telling
    told: bool = False
    # Its latest run, and what that run waits for the person to answer (as its
    # `input.requested` events have them), answered at …/threads/{id}/runs/{run_id}/inputs/{input}
    run_id: UUID | None = None
    requests: list[dict[str, Any]] = []


class ThreadDetail(ThreadOut):
    messages: list[MessageOut]
    # The tasks its agent started in the background, oldest first
    tasks: list[BackgroundTaskOut] = []
    # The agent's latest plan (write_todos), if it made one
    todos: list[dict[str, Any]] = []
    active_run: ActiveRun | None = None


def conversation(values: dict[str, Any]) -> list[MessageOut]:
    """The thread's messages as the user saw them: questions and answers, each turn's answer
    carrying the tools the agent used (tool calls, their results, the provider's web searches)."""
    out: list[MessageOut] = []
    steps: dict[str, Step] = {}
    first_answer: MessageOut | None = None

    def turn_done() -> None:
        nonlocal first_answer
        if steps:
            if first_answer is None:  # tools but no answer (stopped): show them anyway
                first_answer = MessageOut(role="assistant", content="")
                out.append(first_answer)
            first_answer.steps = list(steps.values())
        steps.clear()
        first_answer = None

    for message in values.get("messages", []):
        if isinstance(message, HumanMessage):
            turn_done()
            run_id = (message.id or "").removeprefix(USER_MESSAGE_PREFIX)
            out.append(
                MessageOut(
                    role="user",
                    content=message.text,
                    run_id=run_id if run_id != (message.id or "") else None,
                )
            )
        elif isinstance(message, AIMessage):
            for action in web_actions(message):
                steps[action["id"]] = Step(
                    id=action["id"],
                    name=action["name"],
                    args=action["args"],
                    status="success" if action["completed"] else "error",
                    sources=[Source(**s) for s in action["sources"]],
                )
            for call in message.tool_calls:
                call_id = call.get("id") or ""
                steps[call_id] = Step(
                    id=call_id,
                    name=call["name"],
                    args=json_safe(call.get("args", {}), MAX_TOOL_ARGS),
                )
            if message.text.strip():
                answer = MessageOut(
                    role="assistant",
                    content=message.text,
                    citations=[Source(**c) for c in citations(message)],
                )
                first_answer = first_answer or answer
                out.append(answer)
        elif isinstance(message, ToolMessage) and message.tool_call_id in steps:
            step = steps[message.tool_call_id]
            step.status = (
                "declined"
                if approvals.declined(message.status, message.text)
                else "error"
                if message.status == "error"
                else "success"
            )
            if step.status == "declined":
                # The person's reason, as the agent read it
                step.output = message.text[:MAX_TOOL_OUTPUT]
            step.sources = [Source(**s) for s in tool_sources(message)]
            step.app = apps.step_app(message)
            if step.name == questions.ask_user.name:
                step.output = message.text[:MAX_TOOL_OUTPUT]
            if step.name == "start_async_task" and (
                task := background.started_task(message.text)
            ):
                step.task = task
    turn_done()
    return out


def with_files(messages: list[MessageOut], files: Any) -> list[MessageOut]:
    """Each question with the files attached to it (their note taken off its text, as the
    person wrote it), and each turn's first answer with the files its run shared."""
    by_run: dict[tuple[str, str], list[ChatFileOut]] = {}
    for f in files:
        if f.run_id:
            by_run.setdefault((str(f.run_id), f.origin), []).append(
                ChatFileOut(
                    id=str(f.id),
                    name=f.name,
                    size=f.size,
                    media_type=f.media_type,
                    origin=f.origin,
                )
            )
    for i, message in enumerate(messages):
        if message.role != "user" or not message.run_id:
            continue
        attached = by_run.get((message.run_id, "upload"))
        if attached:
            message.files = attached
            message.content = message.content.removesuffix(
                attached_note([f.name for f in attached])
            )
        shared = by_run.get((message.run_id, "output"))
        if shared:
            answer = next((m for m in messages[i + 1 :] if m.role == "assistant"), None)
            if answer is not None:
                answer.files = shared
    return messages


def with_unfinished(messages: list[MessageOut], ended: set[str]) -> list[MessageOut]:
    """A turn whose run ended without success before the agent wrote anything (stopped at once,
    failed, or waited too long) gets an empty answer, which clients show as "This answer didn't
    finish." (docs/design/screens/chat.md); before, its question stood alone after a reload
    (found by hand: manual-e2e.md, P2-K1). Its steps, if any, already made that answer."""
    out: list[MessageOut] = []
    for i, message in enumerate(messages):
        out.append(message)
        after = messages[i + 1] if i + 1 < len(messages) else None
        if (
            message.role == "user"
            and message.run_id in ended
            and (after is None or after.role == "user")
        ):
            out.append(MessageOut(role="assistant", content=""))
    return out


def with_evaluations(
    messages: list[MessageOut], evaluations: dict[str, Evaluation]
) -> list[MessageOut]:
    """Each graded turn's last answer with the grader's verdict on it."""
    for i, message in enumerate(messages):
        if message.role != "user" or message.run_id not in evaluations:
            continue
        answers = []
        for later in messages[i + 1 :]:
            if later.role == "user":
                break
            answers.append(later)
        if answers:
            answers[-1].evaluation = evaluations[message.run_id]
    return messages


class RunIn(BaseModel):
    message: Annotated[MessageText, Field(min_length=1, max_length=8000)]
    # The chat's permission mode from this message on (approvals.py); none: the chat's current one
    permission_mode: approvals.Mode | None = None
    # Files attached to this message (POST …/files first): put in the environment's /work/in
    # before the turn (chat_files.py)
    files: list[UUID] = Field(default=[], max_length=10)


class ThreadPatch(BaseModel):
    # As long as the title a first message gives (runs/executor.py) and a task's name
    title: str = Field(min_length=1, max_length=80)


def one_line(title: str) -> str:
    """A chat's name as the sidebar and the title bar show it: one line, single spaces."""
    return " ".join(title.split())


def _out(thread: Thread, run_status: str | None = None) -> ThreadOut:
    return ThreadOut(
        id=thread.id,
        title=thread.title,
        created_at=thread.created_at,
        updated_at=thread.updated_at,
        run_status=run_status,
        permission_mode=thread.permission_mode,
        parent_id=thread.parent_id,
    )


async def owned_thread(
    thread_id: UUID, user: CurrentUser, session: Session, request: Request
) -> Thread:
    thread = await session.scalar(
        select(Thread).where(
            Thread.id == thread_id,
            Thread.user_id == user.id,
            Thread.deleted_at.is_(None),
        )
    )
    if thread is None:
        await audit.theirs(request, session, Thread, thread_id, user, "thread")
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Thread not found")
    # The read's transaction ends here, giving its connection back: the request's session lives
    # until its response is sent, a stream's until the stream ends, and holding one per open
    # stream emptied the pool, stalling every other request 25 s (manual-e2e.md, P4-E3). The thread
    # stays readable (expire_on_commit off); a later query takes a connection for itself
    await session.commit()
    return thread


OwnedThread = Annotated[Thread, Depends(owned_thread)]


@router.get("", summary="The caller's threads, most recent first")
async def list_threads(user: CurrentUser, session: Session) -> list[ThreadOut]:
    rows = await session.execute(
        select(Thread, Run.status)
        .outerjoin(
            Run,
            (Run.thread_id == Thread.id) & Run.status.in_(ACTIVE_RUN_STATUSES),
        )
        # A background task's chat is reached from the chat that started it
        .where(
            Thread.user_id == user.id,
            Thread.deleted_at.is_(None),
            Thread.parent_id.is_(None),
        )
        .order_by(Thread.updated_at.desc())
        .limit(100)
    )
    rows = list(rows)
    # A chat whose background task waits for the person needs them too (background.py)
    asking = set(
        await session.scalars(
            select(Thread.parent_id)
            .join(Run, Run.thread_id == Thread.id)
            .where(
                Thread.parent_id.in_([t.id for t, _ in rows]),
                Thread.deleted_at.is_(None),
                Run.status == "waiting",
            )
        )
    )
    return [
        _out(thread, run_status or ("waiting" if thread.id in asking else None))
        for thread, run_status in rows
    ]


@router.post("", status_code=status.HTTP_201_CREATED, summary="Start a thread")
async def create_thread(user: CurrentUser, session: Session) -> ThreadOut:
    thread = Thread(user_id=user.id)
    session.add(thread)
    await session.commit()
    await session.refresh(thread)
    return _out(thread)


async def _tasks(session: Session, thread_id: UUID) -> list[BackgroundTaskOut]:
    """The chat's tasks with their latest run's status, and whether their end was told: a
    notice's run in the chat names that run, or it was stopped (not told), or it ended over a
    day ago (TellChatWorkflow gave up)."""

    def newest(column):
        return (
            select(column)
            .where(Run.thread_id == Thread.id)
            .order_by(Run.created_at.desc())
            .limit(1)
            .scalar_subquery()
        )

    rows = (
        await session.execute(
            select(
                Thread.id,
                Thread.title,
                Thread.created_at,
                newest(Run.id),
                newest(Run.status),
                newest(Run.finished_at),
            )
            .where(Thread.parent_id == thread_id, Thread.deleted_at.is_(None))
            .order_by(Thread.created_at)
        )
    ).tuples()
    noticed = set(
        await session.scalars(
            select(Run.input["notice_of"].astext).where(
                Run.thread_id == thread_id, Run.input.has_key("notice_of")
            )
        )
    )
    rows = list(rows)
    waiting = [run for _, _, _, run, status, _ in rows if status == "waiting"]
    asks: dict[UUID, list[dict[str, Any]]] = {}
    if waiting:
        for run_id, input_id, kind, request in (
            await session.execute(
                select(
                    InputRequest.run_id,
                    InputRequest.id,
                    InputRequest.kind,
                    InputRequest.request,
                )
                .where(
                    InputRequest.run_id.in_(waiting), InputRequest.response.is_(None)
                )
                .order_by(InputRequest.created_at)
            )
        ).tuples():
            asks.setdefault(run_id, []).append(
                store.requested_event(store.Pending(input_id, kind, request)).data
            )
    long_ago = datetime.now(UTC) - timedelta(days=1)
    return [
        BackgroundTaskOut(
            id=task,
            title=title,
            status=status,
            created_at=created,
            told=status == "cancelled"
            or str(run) in noticed
            or bool(finished and finished < long_ago),
            run_id=run,
            requests=asks.get(run, []),
        )
        for task, title, created, run, status, finished in rows
    ]


@router.get(
    "/{thread_id}/tasks",
    summary="The tasks the thread's agent started in the background, with their status",
)
async def list_tasks(thread: OwnedThread, session: Session) -> list[BackgroundTaskOut]:
    return await _tasks(session, thread.id)


@router.get(
    "/{thread_id}", summary="A thread with its messages, and its active run if any"
)
async def get_thread(
    thread: OwnedThread, session: Session, request: Request
) -> ThreadDetail:
    state = await request.app.state.agent.aget_state(
        {"configurable": {"thread_id": str(thread.id)}}
    )
    values = state.values if state and state.values else {}
    messages = with_files(
        conversation(values),
        await session.execute(
            select(
                ChatFile.run_id,
                ChatFile.origin,
                ChatFile.id,
                ChatFile.name,
                ChatFile.size,
                ChatFile.media_type,
            )
            .where(ChatFile.thread_id == thread.id)
            .order_by(ChatFile.created_at)
        ),
    )
    # Which plugin each skill read came from, as its run recorded it
    plugins: dict[str, str] = {
        call_id: plugin
        for call_id, plugin in (
            await session.execute(
                select(RunEvent.data["id"].astext, RunEvent.data["plugin"].astext)
                .join(Run, Run.id == RunEvent.run_id)
                .where(
                    Run.thread_id == thread.id,
                    RunEvent.type == "tool.started",
                    RunEvent.data.has_key("plugin"),
                )
            )
        ).tuples()
    }
    for message in messages:
        for step in message.steps:
            step.plugin = plugins.get(step.id)
    # Background tasks' notices: questions Gen9 wrote (background.py)
    notices = {
        str(run_id)
        for run_id in await session.scalars(
            select(Run.id).where(
                Run.thread_id == thread.id, Run.input.has_key("notice_of")
            )
        )
    }
    # A graded task's next tries: findings its grader wrote (outcomes.py)
    revisions = {
        str(run_id)
        for run_id in await session.scalars(
            select(Run.id).where(
                Run.thread_id == thread.id, Run.input.has_key("revision")
            )
        )
    }
    for message in messages:
        message.notice = message.role == "user" and message.run_id in notices
        message.revision = message.role == "user" and message.run_id in revisions
    # Turns whose run summarized earlier messages (`context.summarized`)
    summarized = {
        str(run_id)
        for run_id in await session.scalars(
            select(RunEvent.run_id)
            .join(Run, Run.id == RunEvent.run_id)
            .where(Run.thread_id == thread.id, RunEvent.type == "context.summarized")
        )
    }
    for i, message in enumerate(messages):
        if message.role == "user" and message.run_id in summarized:
            answer = next((m for m in messages[i + 1 :] if m.role == "assistant"), None)
            if answer is not None:
                answer.summarized = True
    messages = with_unfinished(
        messages,
        {
            str(run_id)
            for run_id in await session.scalars(
                select(Run.id).where(
                    Run.thread_id == thread.id,
                    Run.status.in_(("cancelled", "error", "expired")),
                )
            )
        },
    )
    messages = with_evaluations(
        messages,
        {
            str(e.run_id): Evaluation.model_validate(e, from_attributes=True)
            for e in await session.scalars(
                select(OutcomeEvaluation)
                .join(Run, Run.id == OutcomeEvaluation.run_id)
                .where(Run.thread_id == thread.id)
            )
        },
    )
    run = await session.scalar(
        select(Run).where(
            Run.thread_id == thread.id, Run.status.in_(ACTIVE_RUN_STATUSES)
        )
    )
    active = None
    if run is not None:
        active = ActiveRun(
            id=run.id,
            status=run.status,
            message=run.input["message"],
            notice="notice_of" in run.input,
            revision="revision" in run.input,
        )
        # Show the conversation up to the active run's question: its answer comes from following
        # the run (which replays what it has written so far), not from the unfinished checkpoint
        # Its question: by the run's id on it, or (a run from before ids) by its text
        asked = [
            i
            for i, m in enumerate(messages)
            if m.role == "user"
            and (
                m.run_id == str(run.id)
                or (m.run_id is None and m.content == active.message)
            )
        ]
        messages = (
            messages[: asked[-1] + 1]
            if asked
            else [
                *messages,
                MessageOut(
                    role="user",
                    content=active.message,
                    notice=active.notice,
                    revision=active.revision,
                ),
            ]
        )
    tasks = await _tasks(session, thread.id)
    return ThreadDetail(
        **_out(thread, run.status if run else None).model_dump(),
        messages=messages,
        tasks=tasks,
        todos=json_safe(values.get("todos") or [], 8000) if active is None else [],
        active_run=active,
    )


@router.patch("/{thread_id}", summary="Rename a thread")
async def rename_thread(
    body: ThreadPatch, thread: OwnedThread, session: Session
) -> ThreadOut:
    """The person's own name for the chat. The first answer's title never replaces it (the
    executor names only a chat still called "New chat"), and the chat keeps its place in the
    list: `updated_at` is the conversation's last activity, and a rename isn't one."""
    title = one_line(body.title)
    if not title:
        raise HTTPException(status.HTTP_422_UNPROCESSABLE_CONTENT, "Name the chat.")
    thread.title = title
    run_status = await session.scalar(
        select(Run.status).where(
            Run.thread_id == thread.id, Run.status.in_(ACTIVE_RUN_STATUSES)
        )
    )
    await session.commit()
    return _out(thread, run_status)


@router.delete(
    "/{thread_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete a thread: its running answer, its traces in Langfuse, its history, its runs",
    responses={202: {"description": "Deleting; it finishes on its own"}},
)
async def delete_thread(
    thread: OwnedThread, principal: CurrentPrincipal, session: Session, request: Request
) -> Response:
    """The chat disappears for its owner at once; DeleteThreadWorkflow then stops a running
    answer, erases its Langfuse traces, its runs' history in Temporal, its checkpoints and rows,
    retrying each step until it succeeds (docs/temporal.md). Its background tasks' chats go
    with it, each through a deletion of its own."""
    thread_id, created_at = thread.id, thread.created_at
    tasks = (
        await session.execute(
            select(Thread.id, Thread.created_at).where(
                Thread.parent_id == thread_id, Thread.deleted_at.is_(None)
            )
        )
    ).all()
    now = datetime.now(UTC)
    thread.deleted_at = now
    await session.execute(
        update(Thread).where(Thread.parent_id == thread_id).values(deleted_at=now)
    )
    await session.commit()
    try:
        for task_id, task_created_at in tasks:
            await start_thread_deletion(
                request.app.state.temporal, task_id, task_created_at, principal.sub
            )
        handle = await start_thread_deletion(
            request.app.state.temporal, thread_id, created_at, principal.sub
        )
    except Exception:
        logger.exception("could not start deleting thread %s", thread_id)
        await session.execute(
            update(Thread)
            .where((Thread.id == thread_id) | (Thread.parent_id == thread_id))
            .values(deleted_at=None)
        )
        await session.commit()
        raise HTTPException(
            status.HTTP_503_SERVICE_UNAVAILABLE,
            "The chat can't be deleted right now. Try again in a moment.",
        ) from None
    # The record `make restore` reads to delete it again, should a backup bring it back (P4-E5)
    for deleted in [*(task_id for task_id, _ in tasks), thread_id]:
        await audit.record(request, principal.sub, "thread.delete", target=deleted)
    answer = await finished_or_accepted(handle, THREAD_WAIT_S)
    if answer.status_code == status.HTTP_204_NO_CONTENT and await session.scalar(
        select(Thread.id).where(Thread.id == thread_id)
    ):
        # Its data steps were done, yet the chat is here: a restore brought it back while that
        # deletion still waited to erase late traces, and joining it deleted nothing. One of its
        # own, as gen9-agent-erase starts (gen9-learn plan, M9 T9b)
        handle = await start_thread_deletion(
            request.app.state.temporal, thread_id, created_at, principal.sub, again=True
        )
        answer = await finished_or_accepted(handle, THREAD_WAIT_S)
    return answer
