#!/usr/bin/env bash
# Generate the .env for gen9-sandbox: the API key of OpenSandbox's server. Optionally write
# gen9-agent's settings for it too.
# Portable: bash 3.2+ (macOS and Linux). Run with --help.
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
OUTPUT="$SCRIPT_DIR/.env" AGENT_ENV_FILE="" PORT="20000" FORCE="false" FROM_ENV="false"

usage() {
  cat <<'USAGE'
Generate .env for the gen9-sandbox stack.

Usage: ./init-env.sh [--port N] [--agent-env-file FILE] [-o FILE|-] [--force]
       ./init-env.sh --from-env --agent-env-file FILE [--force]

  --port N               Host port for the server's API (bound to 127.0.0.1)   [20000]
  --agent-env-file FILE  Also write gen9-agent's settings, e.g. ../gen9-agent/sandbox.local.env
  -o, --output FILE      File to write, or - for stdout                       [.env next to this script]
  --force                Overwrite existing output files
  --from-env             Only write --agent-env-file, from the existing .env (for a lost settings file)
USAGE
}

die() { printf 'error: %s\n' "$*" >&2; exit 1; }
rand_hex() { if command -v openssl >/dev/null 2>&1; then openssl rand -hex "$1"; else od -An -vtx1 -N "$1" /dev/urandom | tr -d ' \n'; echo; fi; }

while [ $# -gt 0 ]; do
  case "$1" in
    --*=*) flag=${1%%=*} value=${1#*=}; shift; set -- "$flag" "$value" "$@"; continue ;;
  esac
  case "$1" in
    --port) [ $# -ge 2 ] || die "--port needs a value"; PORT=$2; shift 2 ;;
    --agent-env-file) [ $# -ge 2 ] || die "$1 needs a value"; AGENT_ENV_FILE=$2; shift 2 ;;
    -o | --output) [ $# -ge 2 ] || die "$1 needs a value"; OUTPUT=$2; shift 2 ;;
    --force) FORCE="true"; shift ;;
    --from-env) FROM_ENV="true"; shift ;;
    -h | --help) usage; exit 0 ;;
    *) die "unknown option: $1 (see --help)" ;;
  esac
done

[[ "$PORT" =~ ^[0-9]+$ ]] && [ "$PORT" -ge 1 ] && [ "$PORT" -le 65535 ] || die "--port must be 1-65535"
if [ "$FROM_ENV" = "true" ]; then
  [ -f "$OUTPUT" ] || die "$OUTPUT doesn't exist: run without --from-env to create it"
  [ -n "$AGENT_ENV_FILE" ] || die "--from-env writes --agent-env-file; name it"
  env_value() { sed -n "s/^$1=//p" "$OUTPUT" | tail -n 1; }
  PORT=$(env_value GEN9_SANDBOX_PORT) API_KEY=$(env_value SANDBOX_API_KEY)
  [ -n "$PORT" ] && [ -n "$API_KEY" ] || die "$OUTPUT has no GEN9_SANDBOX_PORT or SANDBOX_API_KEY"
fi
not_there() { if [ -n "$1" ] && [ "$1" != "-" ] && [ -e "$1" ] && [ "$FORCE" != "true" ]; then die "$1 already exists; pass --force to overwrite"; fi; }
not_there "$AGENT_ENV_FILE"
[ "$FROM_ENV" = "true" ] || not_there "$OUTPUT"

[ "$FROM_ENV" = "true" ] || API_KEY=$(rand_hex 32)

render() {
  cat <<ENV
# Generated by init-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not commit.
COMPOSE_PROJECT_NAME=gen9-sandbox
GEN9_SANDBOX_PORT=$PORT
SANDBOX_API_KEY=$API_KEY
ENV
}

write_private() { # $1=path; content on stdin. Written atomically with mode 600.
  local tmp
  tmp=$(umask 077 && mktemp "$(dirname "$1")/.init-env.XXXXXX")
  cat >"$tmp" && chmod 600 "$tmp" && mv -f "$tmp" "$1"
  printf 'wrote %s\n' "$1"
}

if [ "$FROM_ENV" = "true" ]; then :; elif [ "$OUTPUT" = "-" ]; then render; else render | write_private "$OUTPUT"; fi

if [ -n "$AGENT_ENV_FILE" ]; then
  # Host-side values; gen9-agent's compose.yaml sets SANDBOX_URL for its containers
  printf '# gen9-sandbox settings for gen9-agent (generated %s)\nSANDBOX_URL=http://localhost:%s\nSANDBOX_API_KEY=%s\n' \
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$PORT" "$API_KEY" | write_private "$AGENT_ENV_FILE"
fi

if [ "$OUTPUT" != "-" ] && [ "$FROM_ENV" != "true" ] && [ -z "${GEN9_SETUP:-}" ]; then
  cat >&2 <<NEXT

Next:
  docker compose up -d --wait
  API (gen9-agent): http://localhost:$PORT, header OPEN-SANDBOX-API-KEY
NEXT
fi
