#!/usr/bin/env bash
# Generate the .env for gen9-postgres: random passwords for the superuser and each app role.
# Optionally write gen9-agent's connection settings too: its migrate job's, as the owner of its
# database (gen9_agent), and its services', as the role that owns nothing (gen9_agent_app).
# Portable: bash 3.2+ (macOS and Linux). Run with --help.
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
OUTPUT="$SCRIPT_DIR/.env" AGENT_ENV_FILE="" APP_ENV_FILE="" PORT="16000" FORCE="false" FROM_ENV="false"

usage() {
  cat <<'USAGE'
Generate .env for the gen9-postgres stack.

Usage: ./init-env.sh [--port N] [--agent-env-file FILE] [--agent-app-env-file FILE] [-o FILE|-] [--force]
       ./init-env.sh --from-env [--agent-env-file FILE] [--agent-app-env-file FILE] [--force]

  --port N                   Host port for Postgres (bound to 127.0.0.1)      [16000]
  --agent-env-file FILE      Also write gen9-agent's migrate job's settings (the owner, gen9_agent),
                             e.g. ../gen9-agent/postgres.local.env
  --agent-app-env-file FILE  Also write gen9-agent's services' settings (gen9_agent_app),
                             e.g. ../gen9-agent/postgres-app.local.env
  -o, --output FILE          File to write, or - for stdout                   [.env next to this script]
  --force                    Overwrite existing output files
  --from-env                 Only write the settings files named, from the existing .env: generates
                             nothing, so the database keeps working (for a lost or deleted file)
USAGE
}

die() { printf 'error: %s\n' "$*" >&2; exit 1; }
rand_hex() { if command -v openssl >/dev/null 2>&1; then openssl rand -hex "$1"; else od -An -vtx1 -N "$1" /dev/urandom | tr -d ' \n'; echo; fi; }

while [ $# -gt 0 ]; do
  case "$1" in
    --*=*) flag=${1%%=*} value=${1#*=}; shift; set -- "$flag" "$value" "$@"; continue ;;
  esac
  case "$1" in
    --port) [ $# -ge 2 ] || die "--port needs a value"; PORT=$2; shift 2 ;;
    --agent-env-file) [ $# -ge 2 ] || die "$1 needs a value"; AGENT_ENV_FILE=$2; shift 2 ;;
    --agent-app-env-file) [ $# -ge 2 ] || die "$1 needs a value"; APP_ENV_FILE=$2; shift 2 ;;
    -o | --output) [ $# -ge 2 ] || die "$1 needs a value"; OUTPUT=$2; shift 2 ;;
    --force) FORCE="true"; shift ;;
    --from-env) FROM_ENV="true"; shift ;;
    -h | --help) usage; exit 0 ;;
    *) die "unknown option: $1 (see --help)" ;;
  esac
done

[[ "$PORT" =~ ^[0-9]+$ ]] && [ "$PORT" -ge 1 ] && [ "$PORT" -le 65535 ] || die "--port must be 1-65535"
if [ "$FROM_ENV" = "true" ]; then
  [ -f "$OUTPUT" ] || die "$OUTPUT doesn't exist: run without --from-env to create it"
  [ -n "$AGENT_ENV_FILE$APP_ENV_FILE" ] || die "--from-env writes --agent-env-file or --agent-app-env-file; name one"
  env_value() { sed -n "s/^$1=//p" "$OUTPUT" | tail -n 1; }
  PORT=$(env_value GEN9_POSTGRES_PORT) AGENT_DB_PASSWORD=$(env_value GEN9_AGENT_DB_PASSWORD)
  APP_DB_PASSWORD=$(env_value GEN9_AGENT_APP_DB_PASSWORD)
  [ -n "$PORT" ] && [ -n "$AGENT_DB_PASSWORD" ] || die "$OUTPUT has no GEN9_POSTGRES_PORT or GEN9_AGENT_DB_PASSWORD"
  [ -z "$APP_ENV_FILE" ] || [ -n "$APP_DB_PASSWORD" ] ||
    die "$OUTPUT has no GEN9_AGENT_APP_DB_PASSWORD: run make setup, which adds it"
fi
not_there() { if [ -n "$1" ] && [ "$1" != "-" ] && [ -e "$1" ] && [ "$FORCE" != "true" ]; then die "$1 already exists; pass --force to overwrite"; fi; }
not_there "$AGENT_ENV_FILE"
not_there "$APP_ENV_FILE"
[ "$FROM_ENV" = "true" ] || not_there "$OUTPUT"
# Passwords are only read when the data volume is first created: new ones would lock apps out.
if [ "$FROM_ENV" != "true" ] && [ "$OUTPUT" = "$SCRIPT_DIR/.env" ] && command -v docker >/dev/null &&
  docker volume inspect gen9-postgres_postgres_data >/dev/null 2>&1; then
  die "volume gen9-postgres_postgres_data exists; new passwords would not match it.
  start fresh (DELETES ALL DATA): docker compose down -v
  or, if only gen9-agent's settings file is gone: ./init-env.sh --from-env --agent-env-file FILE"
fi

[ "$FROM_ENV" = "true" ] || { AGENT_DB_PASSWORD=$(rand_hex 16); APP_DB_PASSWORD=$(rand_hex 16); }

render() {
  cat <<ENV
# Generated by init-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not commit.
COMPOSE_PROJECT_NAME=gen9-postgres
GEN9_POSTGRES_PORT=$PORT
POSTGRES_PASSWORD=$(rand_hex 16)
GEN9_AGENT_DB_PASSWORD=$AGENT_DB_PASSWORD
GEN9_AGENT_APP_DB_PASSWORD=$APP_DB_PASSWORD
ENV
}

write_private() { # $1=path; content on stdin. Written atomically with mode 600.
  local tmp
  tmp=$(umask 077 && mktemp "$(dirname "$1")/.init-env.XXXXXX")
  cat >"$tmp" && chmod 600 "$tmp" && mv -f "$tmp" "$1"
  printf 'wrote %s\n' "$1"
}

if [ "$FROM_ENV" = "true" ]; then :; elif [ "$OUTPUT" = "-" ]; then render; else render | write_private "$OUTPUT"; fi

# Host-side values; gen9-agent's compose.yaml sets DATABASE_HOST for its containers
agent_settings() { # $1=what for, $2=role, $3=password
  printf '# gen9-postgres settings for gen9-agent: %s (generated %s)\nDATABASE_HOST=localhost\nDATABASE_PORT=%s\nDATABASE_NAME=gen9_agent\nDATABASE_USER=%s\nDATABASE_PASSWORD=%s\n' \
    "$1" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$PORT" "$2" "$3"
}
[ -z "$AGENT_ENV_FILE" ] ||
  agent_settings "its migrate job, as the owner" gen9_agent "$AGENT_DB_PASSWORD" | write_private "$AGENT_ENV_FILE"
[ -z "$APP_ENV_FILE" ] ||
  agent_settings "its API and worker, as the role that owns nothing" gen9_agent_app "$APP_DB_PASSWORD" | write_private "$APP_ENV_FILE"

if [ "$OUTPUT" != "-" ] && [ "$FROM_ENV" != "true" ]; then
  cat >&2 <<NEXT

Next:
  docker compose up -d --wait
  gen9-agent's services: postgresql://gen9_agent_app:<GEN9_AGENT_APP_DB_PASSWORD>@localhost:$PORT/gen9_agent
  its migrations (owner): postgresql://gen9_agent:<GEN9_AGENT_DB_PASSWORD>@localhost:$PORT/gen9_agent
NEXT
fi
