#!/usr/bin/env bash
# Generate the .env for gen9-ui: the session secret and the Valkey password.
# OIDC settings come from gen9-keycloak (keycloak.local.env), not from here.
# Portable: bash 3.2+ (macOS and Linux). Run with --help.
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
OUTPUT="$SCRIPT_DIR/.env" FORCE="false"

usage() {
  cat <<'USAGE'
Generate .env for the gen9-ui stack.

Usage: ./init-env.sh [-o FILE|-] [--force]

  -o, --output FILE   File to write, or - for stdout      [.env next to this script]
  --force             Overwrite an existing output file

Also needed: keycloak.local.env, written by
  ../gen9-keycloak/init-env.sh --ui-env-file ../gen9-ui/keycloak.local.env
USAGE
}

die() { printf 'error: %s\n' "$*" >&2; exit 1; }
rand_hex() { if command -v openssl >/dev/null 2>&1; then openssl rand -hex "$1"; else od -An -vtx1 -N "$1" /dev/urandom | tr -d ' \n'; echo; fi; }

while [ $# -gt 0 ]; do
  case "$1" in
    -o | --output) [ $# -ge 2 ] || die "$1 needs a value"; OUTPUT=$2; shift 2 ;;
    --force) FORCE="true"; shift ;;
    -h | --help) usage; exit 0 ;;
    *) die "unknown option: $1 (see --help)" ;;
  esac
done

if [ "$OUTPUT" != "-" ] && [ -e "$OUTPUT" ] && [ "$FORCE" != "true" ]; then
  die "$OUTPUT already exists; pass --force to overwrite (signs everyone out)"
fi

render() {
  cat <<ENV
# Generated by init-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not commit.
COMPOSE_PROJECT_NAME=gen9-ui
# The bundled services this stack runs. Without valkey, SESSION_STORE_URL names another Valkey or
# Redis (docs/operations.md, "External services")
COMPOSE_PROFILES=valkey
# Encrypts session records in Valkey; changing it signs everyone out
SESSION_SECRET=$(rand_hex 32)
VALKEY_PASSWORD=$(rand_hex 16)
ENV
}

if [ "$OUTPUT" = "-" ]; then
  render
else
  tmp=$(umask 077 && mktemp "$(dirname "$OUTPUT")/.init-env.XXXXXX")
  render >"$tmp" && chmod 600 "$tmp" && mv -f "$tmp" "$OUTPUT"
  printf 'wrote %s\n' "$OUTPUT"
  [ -f "$SCRIPT_DIR/keycloak.local.env" ] || printf 'note: keycloak.local.env is missing; see --help\n' >&2
fi
