"""threads deleted_at: deletion runs as a workflow

Revision ID: 1cefdf9bd55d
Revises: a7c31e0f5b12

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1cefdf9bd55d"
down_revision: str | Sequence[str] | None = "a7c31e0f5b12"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "threads", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("threads", "deleted_at")
    # ### end Alembic commands ###
