#!/usr/bin/env bash
# Generate the .env for gen9-temporal: random passwords for its Postgres superuser and for the role
# Temporal connects as, and the host ports.
# Portable: bash 3.2+ (macOS and Linux). Run with --help.
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
OUTPUT="$SCRIPT_DIR/.env" PORT="18001" UI_PORT="18000" FORCE="false"

usage() {
  cat <<'USAGE'
Generate .env for the gen9-temporal stack.

Usage: ./init-env.sh [--port N] [--ui-port N] [-o FILE|-] [--force]

  --port N           Host port for Temporal's frontend (gRPC), bound to 127.0.0.1   [18001]
  --ui-port N        Host port for Temporal's web UI, bound to 127.0.0.1           [18000]
  -o, --output FILE  File to write, or - for stdout                     [.env next to this script]
  --force            Overwrite an existing output file

gen9-agent reaches Temporal at gen9-temporal:7233 from its containers, and at localhost:18001
when run on the host; with another --port, set TEMPORAL_ADDRESS in gen9-agent/.env.
USAGE
}

die() { printf 'error: %s\n' "$*" >&2; exit 1; }
rand_hex() { if command -v openssl >/dev/null 2>&1; then openssl rand -hex "$1"; else od -An -vtx1 -N "$1" /dev/urandom | tr -d ' \n'; echo; fi; }

while [ $# -gt 0 ]; do
  case "$1" in
    --*=*) flag=${1%%=*} value=${1#*=}; shift; set -- "$flag" "$value" "$@"; continue ;;
  esac
  case "$1" in
    --port) [ $# -ge 2 ] || die "--port needs a value"; PORT=$2; shift 2 ;;
    --ui-port) [ $# -ge 2 ] || die "--ui-port needs a value"; UI_PORT=$2; shift 2 ;;
    -o | --output) [ $# -ge 2 ] || die "$1 needs a value"; OUTPUT=$2; shift 2 ;;
    --force) FORCE="true"; shift ;;
    -h | --help) usage; exit 0 ;;
    *) die "unknown option: $1 (see --help)" ;;
  esac
done

for p in "$PORT" "$UI_PORT"; do
  [[ "$p" =~ ^[0-9]+$ ]] && [ "$p" -ge 1 ] && [ "$p" -le 65535 ] || die "ports must be 1-65535"
done
if [ "$OUTPUT" != "-" ] && [ -e "$OUTPUT" ] && [ "$FORCE" != "true" ]; then
  die "$OUTPUT already exists; pass --force to overwrite"
fi
# Passwords are only read when the data volume is first created: new ones would lock Temporal out
if [ "$OUTPUT" = "$SCRIPT_DIR/.env" ] && command -v docker >/dev/null &&
  docker volume inspect gen9-temporal_postgres_data >/dev/null 2>&1; then
  die "volume gen9-temporal_postgres_data exists; new passwords would not match it.
  start fresh (DELETES ALL WORKFLOW STATE): docker compose down -v"
fi

render() {
  cat <<ENV
# Generated by init-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not commit.
COMPOSE_PROJECT_NAME=gen9-temporal
# The bundled services this stack runs. Without postgres, POSTGRES_SEEDS names another server
# (docs/operations.md, "External services")
COMPOSE_PROFILES=postgres
GEN9_TEMPORAL_PORT=$PORT
GEN9_TEMPORAL_UI_PORT=$UI_PORT
POSTGRES_PASSWORD=$(rand_hex 16)
TEMPORAL_DB_PASSWORD=$(rand_hex 16)
ENV
}

write_private() { # $1=path; content on stdin. Written atomically with mode 600.
  local tmp
  tmp=$(umask 077 && mktemp "$(dirname "$1")/.init-env.XXXXXX")
  cat >"$tmp" && chmod 600 "$tmp" && mv -f "$tmp" "$1"
  printf 'wrote %s\n' "$1"
}

if [ "$OUTPUT" = "-" ]; then render; else render | write_private "$OUTPUT"; fi

if [ "$OUTPUT" != "-" ] && [ -z "${GEN9_SETUP:-}" ]; then
  cat >&2 <<NEXT

Next:
  docker compose up -d --wait
  Web UI: http://localhost:$UI_PORT   Frontend (gRPC): 127.0.0.1:$PORT, namespace gen9
NEXT
fi
