#!/usr/bin/env bash
# Generate tls.local.env for gen9-temporal: a private CA and the one certificate Temporal's own
# services present to each other (internode mTLS). Every port but the frontend's requires it: the
# internal frontend (7236, which trusts its callers as admins), history, matching, the internal
# worker and membership. Other stacks never get it; they call the frontend with a Keycloak token.
# Portable: bash 3.2+, OpenSSL or LibreSSL. Run with --help.
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
OUTPUT="$SCRIPT_DIR/tls.local.env" FORCE="false"
# The name every internode certificate carries; services check it instead of their changing IPs
SERVER_NAME="internode.gen9-temporal"
CA_DAYS=3650 CERT_DAYS=825

usage() {
  cat <<'USAGE'
Generate tls.local.env (internode mTLS for the gen9-temporal stack).

Usage: ./init-tls.sh [-o FILE|-] [--force]

  -o, --output FILE  File to write, or - for stdout            [tls.local.env next to this script]
  --force            Replace an existing file: a new CA and certificate. Then restart the stack
                     (docker compose up -d --wait) so every service uses the new pair.

The certificate lasts 825 days; make doctor warns 30 days before it expires.
USAGE
}

die() { printf 'error: %s\n' "$*" >&2; exit 1; }

while [ $# -gt 0 ]; do
  case "$1" in
    -o | --output) [ $# -ge 2 ] || die "$1 needs a value"; OUTPUT=$2; shift 2 ;;
    --force) FORCE="true"; shift ;;
    -h | --help) usage; exit 0 ;;
    *) die "unknown option: $1 (see --help)" ;;
  esac
done

command -v openssl >/dev/null || die "openssl is required"
case $OUTPUT in -| /*) ;; *) OUTPUT="$PWD/$OUTPUT" ;; esac
if [ "$OUTPUT" != "-" ] && [ -e "$OUTPUT" ] && [ "$FORCE" != "true" ]; then
  die "$OUTPUT already exists; pass --force to replace the CA and certificate"
fi

work=$(umask 077 && mktemp -d)
trap 'rm -rf "$work"' EXIT
cd "$work"

key() { openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 -out "$1" 2>/dev/null; }
cat >ext.cnf <<EXT
[ca]
basicConstraints = critical, CA:true, pathlen:0
keyUsage = critical, keyCertSign, cRLSign
subjectKeyIdentifier = hash
[internode]
basicConstraints = critical, CA:false
keyUsage = critical, digitalSignature
extendedKeyUsage = serverAuth, clientAuth
subjectAltName = DNS:$SERVER_NAME
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid
EXT

key ca.key
openssl req -new -key ca.key -subj "/O=Gen9/CN=Gen9 Temporal internode CA" -out ca.csr
openssl x509 -req -in ca.csr -signkey ca.key -days "$CA_DAYS" -sha256 \
  -extfile ext.cnf -extensions ca -out ca.pem 2>/dev/null
key internode.key
openssl req -new -key internode.key -subj "/O=Gen9/CN=$SERVER_NAME" -out internode.csr
openssl x509 -req -in internode.csr -CA ca.pem -CAkey ca.key -CAcreateserial -days "$CERT_DAYS" \
  -sha256 -extfile ext.cnf -extensions internode -out internode.pem 2>/dev/null
openssl verify -CAfile ca.pem -purpose sslserver internode.pem >/dev/null
openssl verify -CAfile ca.pem -purpose sslclient internode.pem >/dev/null

b64() { openssl base64 -A -in "$1"; }
render() {
  cat <<ENV
# Generated by init-tls.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not commit.
# Internode mTLS for Temporal (base64 PEM, as its config's certData/keyData/caData expect). The CA
# key is not kept: a new certificate means a new CA (./init-tls.sh --force).
TEMPORAL_TLS_SERVER_CA_CERT_DATA=$(b64 ca.pem)
TEMPORAL_TLS_SERVER_CERT_DATA=$(b64 internode.pem)
TEMPORAL_TLS_SERVER_KEY_DATA=$(b64 internode.key)
TEMPORAL_TLS_INTERNODE_SERVER_NAME=$SERVER_NAME
ENV
}

if [ "$OUTPUT" = "-" ]; then
  render
else
  tmp=$(umask 077 && mktemp "$(dirname "$OUTPUT")/.init-env.XXXXXX")
  (cd "$work" && render) >"$tmp" && chmod 600 "$tmp" && mv -f "$tmp" "$OUTPUT"
  printf 'wrote %s (internode certificate for %s, valid %s days)\n' "$OUTPUT" "$SERVER_NAME" "$CERT_DAYS"
fi
